# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZ1qDUp7v54ZRqgpK2TLGIr6aMsM92JC
"""

import numpy as np
list1=np.arrange(9)
result=list1+list1.mean()
print(result)